version: '3.5'
services:
  auth-service:
    container_name: auth-service
    ports:
      - "8081:8081"
    build:
      context: "./src/main/kotlin/com/example/services/authService/Dockerfile"
      dockerfile: "Dockerfile"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/theatredb"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    networks:
      - dev

  hall-service:
    container_name: hall-service
    ports:
      - "8082:8082"
    build:
      context: "./src/main/kotlin/com/example/services/hallService/Dockerfile"
      dockerfile: "Dockerfile"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/theatredb"
    networks:
      - dev

  reservation-service:
    container_name: reservation-service
    ports:
      - "8083:8083"
    build:
      context: "./src/main/kotlin/com/example/services/reservationService/Dockerfile"
      dockerfile: "Dockerfile"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/theatredb"
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
    networks:
      - dev

  base-service:
    container_name: base-service
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/theatredb"
    networks:
      - dev

  seance-service:
    container_name: seance-service
    ports:
      - "0.0.0.0:8084:8084"
    build:
      context: "./"
      dockerfile: "src/main/kotlin/com/example/services/seanceService/Dockerfile"
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/theatredb"
    networks:
      - dev

  database:
    container_name: database
    image: postgres:latest
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: root
       POSTGRES_DB: theatredb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  db-data:
    driver: local
